classNeed/config/routes.rb
Football::Application.routes.draw do
  resources :contacts

  resources :campaigns

  resources :members

  resources :needs

  resources :class_needs

  resources :project_messages

  resources :users

  resources :locations

  root :to => 'locations#index'

  

  match ':controller(/:action(/:id))(.:format)'
end

classNeed/app/models/campaign.rb
class Campaign < ActiveRecord::Base
  attr_accessible :email_body, :fax_body, :sms_body, :title
  has_many :needs
  
  validates :sms_body, :length => { :maximum => 160 }
end

classNeed/app/controllers/campaigns_controller.rb
require 'clickatell'

class CampaignsController < ApplicationController
  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = Campaign.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @campaigns }
    end
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
    @campaign = Campaign.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @campaign }
    end
  end

  # GET /campaigns/new
  # GET /campaigns/new.json
  def new
    @campaign = Campaign.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @campaign }
    end
  end

  # GET /campaigns/1/edit
  def edit
    @campaign = Campaign.find(params[:id])
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(params[:campaign])

    respond_to do |format|
      if @campaign.save
        
        api = Clickatell::API.authenticate('3409342', 'evelyn02', 'Na57jrZF')
        api.send_message('353879190131', @campaign.sms_body)
        
        open('url')
        
       
        
        
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render json: @campaign, status: :created, location: @campaign }
      else
        format.html { render action: "new" }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /campaigns/1
  # PUT /campaigns/1.json
  def update
    @campaign = Campaign.find(params[:id])

    respond_to do |format|
      if @campaign.update_attributes(params[:campaign])
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign = Campaign.find(params[:id])
    @campaign.destroy

    respond_to do |format|
      format.html { redirect_to campaigns_url }
      format.json { head :no_content }
    end
  end
end

classNeed/app/helpers/campaigns_helper.rb
module CampaignsHelper
end

classNeed/app/views/campaigns/_form.html.erb
<%= form_for(@campaign) do |f| %>
  <% if @campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
      <% @campaign.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
   <div class="field">
    <%= f.label :sms_body %><br />
    <%= f.text_area :sms_body %>
  </div>
  <div class="field">
    <%= f.label :email_body %><br />
    <%= f.text_area :email_body %>
  </div>
  <div class="field">
    <%= f.label :fax_body %><br />
    <%= f.text_area :fax_body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

classNeed/app/views/campaigns/edit.html.erb
<h1>Editing campaign</h1>

<%= render 'form' %>

<%= link_to 'Show', @campaign %> |
<%= link_to 'Back', campaigns_path %>

classNeed/app/views/campaigns/index.html.erb
<h1>Listing campaigns</h1>

<table>
  <tr>
    <th>Title</th>
       <th>Sms body</th>
    <th>Email body</th>
    <th>Fax body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @campaigns.each do |campaign| %>
  <tr>
    <td><%= campaign.title %></td>
        <td><%= campaign.sms_body %></td>
    <td><%= campaign.email_body %></td>
    <td><%= campaign.fax_body %></td>
    <td><%= link_to 'Show', campaign %></td>
    <td><%= link_to 'Edit', edit_campaign_path(campaign) %></td>
    <td><%= link_to 'Destroy', campaign, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Campaign', new_campaign_path %>

classNeed/app/views/campaigns/new.html.erb
<h1>New campaign</h1>

<%= render 'form' %>

<%= link_to 'Back', campaigns_path %>

classNeed/app/views/campaigns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @campaign.title %>
</p>

<p>
  <b>Sms body:</b>
  <%= @campaign.sms_body %>
</p>

<p>
  <b>Email body:</b>
  <%= @campaign.email_body %>
</p>

<p>
  <b>Fax body:</b>
  <%= @campaign.fax_body %>
</p>


<%= link_to 'Edit', edit_campaign_path(@campaign) %> |
<%= link_to 'Back', campaigns_path %>