classNeed/config/routes.rb
Football::Application.routes.draw do
  resources :contacts

  resources :campaigns

  resources :members

  resources :needs

  resources :class_needs

  resources :project_messages

  resources :users

  resources :locations

  root :to => 'locations#index'

  

  match ':controller(/:action(/:id))(.:format)'
end

classNeed/app/models/member.rb
class Member < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :password


end

classNeed/app/controllers/members_controller.rb
class MembersController < ApplicationController
  # GET /members
  # GET /members.json
  def index
    @members = Member.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @members }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/new
  # GET /members/new.json
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(params[:member])

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render json: @member, status: :created, location: @member }
      else
        format.html { render action: "new" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.json
  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end
end

classNeed/app/helpers/members_helper.rb
module MembersHelper
end

classNeed/app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
 
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
  <%= f.label :password, "Password" %><br />
    <%= f.password_field :password %>
 </div>
    <div class="field">
      <%= f.label :password_confirmation, "Password confirmation" %><br />
    <%= f.password_field :password_confirmation %>
     </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

classNeed/app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

classNeed/app/views/members/index.html.erb
<h1>Listing members</h1>

<table>
  
<% @members.each do |member| %>
<%= f.label :first_name, "First Name:" %>
    <%= f.text_field :first_name %>
    <%= f.label :last_name, "Last Name" %>
    <%= f.text_field :last_name %>
    <%= f.label :email, "E-mail" %>
    <%= f.text_field :email %>

    <%= f.label :password, "Password" %>
    <%= f.password_field :password %>
  <tr>
    <td><%= member.first_name %></td>
    <td><%= member.last_name %></td>
    <td><%= member.email %></td>
    <td><%= member.password %></td>
    
    <td><%= link_to 'Show', member %></td>
    <td><%= link_to 'Edit', edit_member_path(member) %></td>
    <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Member', new_member_path %>

classNeed/app/views/members/new.html.erb
<h2>Sign Up</h2>

<%= render 'form' %>
<h2> Login </h2>

<%= link_to 'Back', members_path %>

classNeed/app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @member.first_name %>
</p>

<p>
  <b>String:</b>
  <%= @member.string %>
</p>

<p>
  <b>Last name:</b>
  <%= @member.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @member.email %>
</p>

<p>
  <b>Password:</b>
  <%= @member.password %>
</p>


<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>